image: maven:latest

cache:
  paths:
    - ~/.m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile
  tags:
    - general

test:
  stage: test
  script:
    - mvn test
  tags:
    - opencl

deploy:
  stage: deploy
  script:
    - mvn -DskipTests=true deploy
  tags:
    - general
  only:
    - master
