image: maven:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

code_quality:
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'

cache:
  paths:
    - ~/.m2/repository/
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  tags:
    - general

test-nvidia-gpu:
  image: aparapi/aparapi-nvidia:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" != *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - opencl

test-nvidia-cpu:
  image: aparapi/aparapi-nvidia:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" == *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - compute

test-amdgpu-cpu:
  image: aparapi/aparapi-amdgpu:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" == *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - compute

test-pocl-cpu:
  image: aparapi/aparapi-pocl:latest
  stage: test
  script:
    - clinfo
    - if [[ "$(clinfo | grep 'Device Type')" == *"GPU"* ]]; then exit -1; fi
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - compute

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests=true deploy
  tags:
    - general
  only:
    - master
    - /^v.*$/
